### ISSUE TITLE
how to save or load a trained network ?

### ISSUE THREAD

**Issue by kenchan97** [cbovar/ConvNetSharp#105]
i can not find the network.save api
is it possible to do so ?

**Comment by cbovar** [comment]
Hi, you can take a look [here](https://github.com/cbovar/ConvNetSharp#save-and-load-network)

## Save and Load Network
### JSON serialization (not supported by FluentNet)
```c#
// Serialize to json 
var json = net.ToJsonN();

// Deserialize from json
Net deserialized = SerializationExtensions.FromJson<double>(json);
```

**Comment by kenchan97** [comment]
thanks mate :)
