### ISSUE TITLE
More detailed example for Network Serialization (Save / Load)

### ISSUE THREAD

**Issue by marcteys** [cbovar/ConvNetSharp#124]
In the readme.md you state that to lsave and load you have to use : 

```c#
// Serialize to json 
var json = net.ToJsonN();

// Deserialize from json
Net deserialized = SerializationExtensions.FromJson<double>(json);
```

We cannot use these functions with the current examples, and the function `ToJsonN` cannot be seen on any file of the repo.  It is not clear how to use this and which dependencies are required, and a more detailed example (or the readme or another example in the solution)  will be appreciated. 

You might mention that we need to add the dependency `using ConvNetSharp.Core.Serialization;` and that to save the Network, we have to call `var json = SerializationExtensions.ToJson<double>(net);`

**Comment by cbovar** [comment]
Thanks ! I will fix the code sample, and improve documentation on that.
