### ISSUE TITLE
Creating convolutional network?

### ISSUE THREAD

**Issue by CherryGoose** [cbovar/ConvNetSharp#134]
Im trying to create a convolutional network.  What am i doing wrong? Also can you tell me what kind of methods of training used for every type of network? I using your framework for research purposes and if you can give me references to papers or algorithms that you used that would be great. 
net.AddLayer(new InputLayer(UserData[0].GetLength(0), 1, 1));
            for (int i = 0; i < NumberOfHiddenLayers; i++)
            {
                int size;
                if (UserData[0].GetLength(0) < NumberOfHiddenLayers)
                {
                    size = UserData[0].GetLength(0);
                }
                else
                {
                    size = UserData[0].GetLength(0) / NumberOfHiddenLayers;
                }
                if (size < 2)
                    size = 2;
                net.AddLayer(new ConvLayer((UserData[0].GetLength(0) - i * size), 1, 1));
                net.AddLayer(new ReluLayer());
            }
            net.AddLayer(new ConvLayer(2, 1, 1));
            net.AddLayer(new SoftmaxLayer(2));

**Comment by cbovar** [comment]
Sorry I haven't replied, I was quite busy. You added 'solved' in the title. Should I close this issue?
