### ISSUE TITLE
TrainerBase class is not updated in NuGet

### ISSUE THREAD

**Issue by Jekillokda** [cbovar/ConvNetSharp#140]
When installed from NuGet there is an exception while training network. When looked in TrainerBase class saw that methods have no code in them.
![error](https://user-images.githubusercontent.com/20152316/57605828-33f51f00-7570-11e9-9f1f-dc3ed5be6026.png)

**Comment by cbovar** [comment]
What was the exception ?

**Comment by Jekillokda** [comment]
The index was outside the bounds of the array
![22](https://user-images.githubusercontent.com/20152316/57677365-569a3d00-762f-11e9-9e1b-34a974c9e42b.png)

**Comment by Jekillokda** [comment]
I changed the number of classes to 5 and after that got Volume should have a "Shape [1] to be converter to a System.Double" exception. Looked for such problem. Found that it is because of dropout layers. Deleted them has everything OK. You fixed this problem, but it is still in Nuget Core package. BTW thanks for your work, this is awesome.

**Comment by cbovar** [comment]
Usually "index was outside the bounds of the array" errors are due to incompatible shapes between layers. Globally ConvNetSharp should be improved to throw clearer exceptions.

**Comment by Jekillokda** [comment]
Hello again. You fixed DropoutlLayer problem oin fix #132 on 16 Sep 2018, but last nuget package was published on July 14, 2018. It would be great if you 
it would be nice if you update package with these improvements. Thanks

**Comment by cbovar** [comment]
I will publish a new package soon

**Comment by cbovar** [comment]
I have created updated the nuget packages.

**Comment by Jekillokda** [comment]
Thanks)
