### ISSUE TITLE
how to create 1d Convolutional network with pading?

### ISSUE THREAD

**Issue by lazerdust** [cbovar/ConvNetSharp#147]
in 2d padding added to all borders. in 1d pad must add only on two borders

**Comment by cbovar** [comment]
It seems that padding is applied on 2 dimensions for the moment. Here are the lines where the padding is applied:

_Double_
https://github.com/cbovar/ConvNetSharp/blob/master/src/ConvNetSharp.Volume/Double/Volume.cs#L164-L167
https://github.com/cbovar/ConvNetSharp/blob/master/src/ConvNetSharp.Volume/Double/Volume.cs#L220-L223

_Single_
https://github.com/cbovar/ConvNetSharp/blob/master/src/ConvNetSharp.Volume/Single/Volume.cs#L161-L164
https://github.com/cbovar/ConvNetSharp/blob/master/src/ConvNetSharp.Volume/Single/Volume.cs#L217-L221

_GPU double_
https://github.com/cbovar/ConvNetSharp/blob/master/src/ConvNetSharp.Volume.GPU/Double/Volume.cs#L265
https://github.com/cbovar/ConvNetSharp/blob/master/src/ConvNetSharp.Volume.GPU/Double/Volume.cs#L332

_GPU single_
https://github.com/cbovar/ConvNetSharp/blob/master/src/ConvNetSharp.Volume.GPU/Single/Volume.cs#L264
https://github.com/cbovar/ConvNetSharp/blob/master/src/ConvNetSharp.Volume.GPU/Single/Volume.cs#L336

`ConvLayer<T>.UpdateOutputSize()` methods should be updated too.

Would you like to give it a try ?

**Comment by lazerdust** [comment]
Yes. Where to commit? branch? Access?

**Comment by cbovar** [comment]
You can fork this repo, create a branch, commit your changes (code and tests) on that branch and then create a pull request from that branch. I will review it and merge it.
