### ISSUE TITLE
"disposable" not defined

### ISSUE THREAD

**Issue by gschmidt958** [cbovar/ConvNetSharp#152]
Hello,
I just downloaded and tried to build ConvNetSharp.Core.2015 with VS2015 and I obtain the following error.

![image](https://user-images.githubusercontent.com/5486583/79644879-c5eeaa00-8179-11ea-94f8-22e9fc2d505f.png)

Thanks!

**Comment by cbovar** [comment]
Hi! 
You need VS2019 to build ConvNetSharp. You get this error because it uses a language feature that doesn't exist yet in VS2015.

Also, is your repository up-to-date? I believe I removed 2015 related stuff long time ago.

**Comment by gschmidt958** [comment]
Hi,
I pulled down the repo in a zip file today.  There was a project file which had "2015" in the name which I used.  I can install VS2019, if that is what is needed.
Thank you for your response.

**Comment by cbovar** [comment]
2015 projects were removed in this [commit](https://github.com/cbovar/ConvNetSharp/commit/83f8ca0b2f45e96cb76001da881d39e62bbfac6e)  on Jul 14, 2018. 

Maybe try to clone this repo or download the [zip](https://github.com/cbovar/ConvNetSharp/archive/master.zip) again ?
The latest version is https://github.com/cbovar/ConvNetSharp/archive/master.zip

**Comment by gschmidt958** [comment]
I downloaded the latest repo and installed VS2019.  I now have the 2D demo running :)
Thanks again!

**Comment by dellaram** [comment]
Just wanna learn programming and data but have no source.
