### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lazerdust** [cbovar/ConvNetSharp#156]
Why you use
https://github.com/cbovar/ConvNetSharp/blob/ccaf6f6959c12026c4e1a0e396a7711654c92551/src/ConvNetSharp.Core/Layers/FullyConnLayer.cs#L82
Convolution
not MatMultiply
?

**Comment by cbovar** [comment]
Hi,
I believe that at the time I had not implemented the MatMultiply but convolution was already wired so it was easier.

**Comment by lazerdust** [comment]
MatMultiply use Cuda.
convolution use cudnn.
I checked MatMultiply and convolution. Convolution is faster than  MatMultiply. Because cudnn is faster than cuda
