### ISSUE TITLE
IVolume does not contain definition for WeightGradients.

### ISSUE THREAD

**Issue by rajan-sunder** [cbovar/ConvNetSharp#26]
The WeightGradients is a private double in Volume class but no definition in IVolumne. This will result in error in class FullyConnLayer when you use.

var temp = volume.WeightGradients;

**Comment by cbovar** [comment]
Thanks! I hadn't test without defining PARRALEL symbol. It should be fine now.

Note that weights and gradients are accessed using Get and GetGradient methods now.

**Comment by rajan-sunder** [comment]
Thanks
