### ISSUE TITLE
Bug in AdagradTrainer

### ISSUE THREAD

**Issue by gianlucabertani** [cbovar/ConvNetSharp#29]
Hello,

there's a minor bug in AdagradTrainer at line 81. It currently reads:

```csharp
    vol.SetGradient(i, 0.0); // zero out gradient so that we can begin accumulating anew
```

But in that point the correct index to use is **j**, not **i**:

```csharp
    vol.SetGradient(j, 0.0); // zero out gradient so that we can begin accumulating anew
```

Forgive me if I don't submit a pull request, my fork has some more commits on top and branching just for this little fix would be a bit of a hassle.
Thanks again for your great work!

**Comment by cbovar** [comment]
Hi,

Thank you! I have commited the fix on the main branch.

Regards,
Cedric
