### ISSUE TITLE
Example needs to be updated (Volume.Weights cannot be accessed)

### ISSUE THREAD

**Issue by peabnuts123** [cbovar/ConvNetSharp#30]
The example in README.md refers to `prob.Weights[0]`. However, as per [this commit](https://github.com/cbovar/ConvNetSharp/commit/b42fffe25198142e8c8d7acc7e5473be4997ccb4#diff-cb8fa77ab91d6929ea9f06ade2cc09df) the `.Weights` field in Volume is now private and must be accessed via `.Get()`. Really minor change, just kind of annoying since the provided example doesn't actually compile and forces one to dig through the commit history to figure out how to fix it!

**Comment by cbovar** [comment]
I fix this right now. Thanks!
