### ISSUE TITLE
Torch model

### ISSUE THREAD

**Issue by mphielipp** [cbovar/ConvNetSharp#31]
Great library, only one in C#!! 

I was trying to load a torch model but it was impossible to set up weights and biases to see if ConvNetSharp has the same data order.  Any efforts on this side? How can I test if the model I build with V will be the same as Torch, at least for the basic layers; SpatialConvolutionMM, Relus, Linea, etc.

**Comment by cbovar** [comment]
I guess you could dump in a file the output of layers in Torch and in ConvNetSharp and compare?

I think that Torch uses Cudnn. A new version of ConvnNetSharp with the possibility to use Cudnn will come out soon. The tests will show that CPU computations and GPU Cudnn computations actually yield the same result.

**Comment by mphielipp** [comment]
The issue is that you can not change the weights and the biases in ConvNetSharp without changes the properties to public, etc. Or at least I did not find a way to try that without changing those properties.

**Comment by radioman** [comment]
its not a stone, you can change it ;}

**Comment by cbovar** [comment]
Weights are stored in Volumes. Volumes are usually public (eg. `ConvLayer.Bias`,` ConvLayer.Filters`, `FullyConnLayer.Bias`, `FullyConnLayer.Filters` etc.) 

E.g. In this unit test, some weights are set https://github.com/cbovar/ConvNetSharp/blob/master/src/ConvNetSharp.Tests/FullyConnLayerTests.cs#L37

**Comment by mphielipp** [comment]
Thanks!!
