### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by Daemon2017** [cbovar/ConvNetSharp#34]
After 27.3.17 update, I can't build any examples - project's files ConvNetSharp.Core and ConvNetSharp.Volume couldn't be loaded.

Error list:
1) _There is no target object "GetTargetPath"_ at file _ConvNetSharp.Volume.csproj_
2) _Unrecognized "Version" attribute in the <PackageReference>_ at file _ConvNetSharp.Core.csproj_

**Comment by cbovar** [comment]
Hi. Which version of VS so you use?
I used vs 2017 for dot net standard.

**Comment by Daemon2017** [comment]
Hello! 
VS2015 Community. 
![image](https://cloud.githubusercontent.com/assets/5642326/24382138/fa2cbb60-135c-11e7-8f5e-12b2afadb09e.png)

_The default XML namespace for this project must be the MSBuild XML namespace. If the project is created in MSBuild 2003 format, add xmlns = "http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project was created in the old 1.0 or 1.2 format, convert it to MSBuild 2003 format._

When I've added _xmlns = "http://schemas.microsoft.com/developer/msbuild/2003"_ then the result is:
![image](https://cloud.githubusercontent.com/assets/5642326/24382172/3ccc3bb2-135d-11e7-8be2-8b08889dadad.png)

**Comment by cbovar** [comment]
I will make a vs2015 branch, probably today

**Comment by Daemon2017** [comment]
Thank you!

I've installed VS2015 Update 3 and .NET Core 1.0.1, but it doesn't help:
![image](https://cloud.githubusercontent.com/assets/5642326/24394090/43ba946e-13a3-11e7-925a-634d6a31e851.png)

**Comment by cbovar** [comment]
Here it is: https://github.com/cbovar/ConvNetSharp/tree/vs2015
Please let me know if everything is fine.

**Comment by Daemon2017** [comment]
Unfortunately, now I receive new errors:
![image](https://cloud.githubusercontent.com/assets/5642326/24431617/a32e6984-1425-11e7-957a-ed2dcf2ff7dd.png)

The main one is _Syntax error, required ","_. Her additional variants is
 _The name "loss" does not exist in the current context_.
![image](https://cloud.githubusercontent.com/assets/5642326/24432009/fb79aa5c-1427-11e7-9ec5-70eb2136e560.png)
![image](https://cloud.githubusercontent.com/assets/5642326/24432049/323f3f3e-1428-11e7-9ceb-23cd61143133.png)
and _"T" is a type, but used as variable_
![image](https://cloud.githubusercontent.com/assets/5642326/24432028/177209f2-1428-11e7-8dc2-2bc604a0d7d4.png)

Additional error is _Can not find metadata file "...\ConvNetSharp-vs2015\src\ConvNetSharp.Core\bin\Debug\ConvNetSharp.Volume.Tests.dll"._
I think, that I can just build it, but I can't because of previous errors.

**Comment by cbovar** [comment]
I see. It's a c# 7 feature not supported in vs2015. I correct this in a few minutes.

**Comment by cbovar** [comment]
I committed the fix and tested on a vs2015.

**Comment by Daemon2017** [comment]
Thank you!
Now it works perfect :)
