### ISSUE TITLE
Serialization from Json doesn't work

### ISSUE THREAD

**Issue by hiperz** [cbovar/ConvNetSharp#43]
Hello,

![image](https://cloud.githubusercontent.com/assets/28654452/26050937/893edd88-399b-11e7-9cf9-41ae2800e2c8.png)

![image](https://cloud.githubusercontent.com/assets/28654452/26050818/169b511c-399b-11e7-991a-f356c8a54fad.png)

System.MissingMethodException: ''ConvNetSharp.Core.Layers.Single.ConvLayer'

**Comment by cbovar** [comment]
Tests should be made generic (single/double) so we can catch such errors earlier

**Comment by cbovar** [comment]
This issue should be fix by commit 220d253 but I leave this issue open until the corresponding test is written.

**Comment by raBpywa** [comment]
SerializationExtensions.FromJson<double>(opennetwork); 
for RegressionLayer - Error (Constructor not found);

> -		$exception	{"Конструктор для типа \"ConvNetSharp.Core.Layers.Double.RegressionLayer\" не найден."}	System.MissingMethodException

**Comment by cbovar** [comment]
commit 7af73fd should fix that. Thanks
