### ISSUE TITLE
NuGet?

### ISSUE THREAD

**Issue by lostmsu** [cbovar/ConvNetSharp#46]
Seems like an awesome project. Can you make it available on NuGet?

**Comment by Daemon2017** [comment]
I join the request. Availability on NuGet would be awesome :)

**Comment by cbovar** [comment]
I understand Nuget is very practical. Since it is not stable, I will publish it Nuget as pre-release.

**Comment by cbovar** [comment]
`Install-Package Cognitio.ConvNetSharp.Core -Pre`

I only have published vs2015 version. I have to figure out how to publish multiple target packages.

**Comment by cbovar** [comment]
`Install-Package Cognitio.ConvNetSharp.Volume -Pre`
`Install-Package Cognitio.ConvNetSharp.Core -Pre`
`Install-Package Cognitio.ConvNetSharp.Volume.GPU -Pre`

Volume and Core target `net45` `net46` `netstandard1.4`
Volume.GPU targets `net45`
