### ISSUE TITLE
CUDA implementation seems to be leaking memory somewhere

### ISSUE THREAD

**Issue by lostmsu** [cbovar/ConvNetSharp#47]
I might work on it soon, if you guys don't have time.

This is what I do:
```csharp
using (var input = new Volume(inputs, new Shape(SolutionStateImageRenderer.ImageWidth, SolutionStateImageRenderer.ImageHeight, 1, minibatch.Length)))
using (var expectedOutput = new Volume(outputs, new Shape(1, 1, classCount, minibatch.Length)))
    this.trainer.Train(input, expectedOutput);
```
Repeating this multiple times eventually leads to Cuda ErrorOutOfMemory
With some added debug code I can see, that total deallocation in 1 iteration is less than allocation.

**Comment by cbovar** [comment]
Yes, I am not happy with the current design which makes too much allocations (+probably memory not being released properly, leading to leaks).

I am currently working on another version of ConvNetSharp which will make the code clearer, with less allocations. I have good hope it will solve many issues, that's why I am not spending too much time fixing the current version).

**Comment by lostmsu** [comment]
Is it not in one of the branches here? I would be interested to see/contribute.

**Comment by cbovar** [comment]
Great :+1: 
I will commit what's being done this week end. 

Basically it looks a lot like tensor flow.

**Comment by lostmsu** [comment]
BTW, I've noticed, that despite being convenient for generalization, Ops<T> is quite slow due to delegate invocation calls.

**Comment by cbovar** [comment]
Yes. Ideally, Ops should not be used. I think it will not be needed anymore in the next version.

I will commit today on a branch what I have done so far.

**Comment by cbovar** [comment]
You can check out the Develop branch: https://github.com/cbovar/ConvNetSharp/tree/Develop

**Comment by omittones** [comment]
I think I fixed the memory leak, it was during the ReShape that was happening.

**Comment by cbovar** [comment]
@omittones Thanks! I will close this then.
