### ISSUE TITLE
MnistDemo crashes

### ISSUE THREAD

**Issue by lu8848** [cbovar/ConvNetSharp#48]
Everytime when I run MnistDemo, it throws ArgumentException and then crashes the app. Before cashes, the test accuracy comes up to 85% and then drop back to 4%.

The exception comes from LayerBase.DoForward().

        public virtual Volume<T> DoForward(Volume<T> input, bool isTraining = false)
        {
#if DEBUG
            var inputs = input.ToArray();
            foreach(var i in inputs)
                if (Ops<T>.IsInvalid(i))
                    throw new ArgumentException("Invalid input!");
#endif
...

Branch: master
IDE: VS2017 and VS2015

Has anybody tested it? I can reproduce it every time.

**Comment by cbovar** [comment]
It happens to me too.

This exception means that the gradients exploded. It is most likely due to an error somewhere in the gradient computation. MnistDemo.GPU seems fine so the error should be in CPU computation.

Try replacing `SgdTrainer` by `AdamTrainer` in Mnist demo.

**Comment by cbovar** [comment]
It should be fine now.
