### ISSUE TITLE
How exactly one goes about learning XOR in with this tool?

### ISSUE THREAD

**Issue by mvrozanti** [cbovar/ConvNetSharp#59]
I don't get the concept of 'classes' of the README example. 

I know the purpose of this tool is to deal with multidimensional input but I'm a bit stuck

**Comment by elamaunt** [comment]
Hi!
I tried to implement same code with convnetjs from https://gist.github.com/willguitaradmfar/12f7efb2ab9534755619ba4dce72f988

Js sample works fine:
![image](https://user-images.githubusercontent.com/804384/32678960-7958aa7a-c686-11e7-9228-e2c589eb10ff.png)

But same code on sharp doesnt give same result:

            var net = new Net<double>();
            
            net.AddLayer(new InputLayer(1, 1, 2));

            net.AddLayer(new FullyConnLayer(3));
            net.AddLayer(new TanhLayer());

            net.AddLayer(new FullyConnLayer(2));
            net.AddLayer(new SoftmaxLayer(2));


            var x0 = new Volume(new double[] { 1, 1 }, new Shape(2));
            var x1 = new Volume(new double[] { 0, 1 }, new Shape(2));
            var x2 = new Volume(new double[] { 1, 0 }, new Shape(2));
            var x3 = new Volume(new double[] { 0, 0 }, new Shape(2));
            
            Console.WriteLine("x0: " + net.Forward(x0).Get(0));
            Console.WriteLine("x1: " + net.Forward(x1).Get(0));
            Console.WriteLine("x2: " + net.Forward(x2).Get(0));
            Console.WriteLine("x3: " + net.Forward(x3).Get(0));

            Console.WriteLine();
            Console.WriteLine();
            
            var trainer = new SgdTrainer<double>(net) { LearningRate = 0.2, L2Decay = 0.001 };
            
            for (int i = 0; i < 2000; i++)
            {
                trainer.Train(x0, new Volume(new double[] { 0.0 }, new Shape(1)));
                trainer.Train(x1, new Volume(new double[] { 1.0 }, new Shape(1)));
                trainer.Train(x2, new Volume(new double[] { 1.0 }, new Shape(1)));
                trainer.Train(x3, new Volume(new double[] { 0.0 }, new Shape(1)));
            }

            Console.WriteLine("x0: " + net.Forward(x0).Get(0));
            Console.WriteLine("x1: " + net.Forward(x1).Get(0));
            Console.WriteLine("x2: " + net.Forward(x2).Get(0));
            Console.WriteLine("x3: " + net.Forward(x3).Get(0));


![image](https://user-images.githubusercontent.com/804384/32679615-d40822b4-c688-11e7-86cf-2ed247dddb3d.png)

Perhaps there are some errors in my code or in the project code.

**Comment by elamaunt** [comment]
Changing of shape changes results. I could not understand how does shapes work =/

**Comment by mvrozanti** [comment]
I've given up on C# approaches. Python is much more readable and while it may not be as 'debuggable' it is easier to understand where you're screwing up. Also so many **good** libraries.

**Comment by cbovar** [comment]
From issue #74
```csharp
var net = new Net<double>();
net.AddLayer(new InputLayer(1, 1, 2)); // Two inputs
net.AddLayer(new FullyConnLayer(3));
net.AddLayer(new TanhLayer());
net.AddLayer(new FullyConnLayer(2));
net.AddLayer(new SoftmaxLayer(2)); // Two possible outcome/class (0 and 1)

// All possible inputs
var x0 = new Volume(new double[] { 1, 1 }, new Shape(2));
var x1 = new Volume(new double[] { 0, 1 }, new Shape(2));
var x2 = new Volume(new double[] { 1, 0 }, new Shape(2));
var x3 = new Volume(new double[] { 0, 0 }, new Shape(2));

var trainer = new SgdTrainer<double>(net) { LearningRate = 0.2 };

for (var i = 0; i < 2000; i++)
{
    trainer.Train(x0, new Volume(new[] { 1.0, 0.0 }, new Shape(1, 1, 2, 1)));
    trainer.Train(x1, new Volume(new[] { 0.0, 1.0 }, new Shape(1, 1, 2, 1)));
    trainer.Train(x2, new Volume(new[] { 0.0, 1.0 }, new Shape(1, 1, 2, 1)));
    trainer.Train(x3, new Volume(new[] { 1.0, 0.0 }, new Shape(1, 1, 2, 1)));

    Console.WriteLine(trainer.Loss); // Should decrease
}

Console.WriteLine("x0: " + net.Forward(x0).Get(0));
Console.WriteLine("x1: " + net.Forward(x1).Get(0));
Console.WriteLine("x2: " + net.Forward(x2).Get(0));
Console.WriteLine("x3: " + net.Forward(x3).Get(0));

Console.ReadLine();
```
