### ISSUE TITLE
GPU implementation

### ISSUE THREAD

**Issue by cbovar** [cbovar/ConvNetSharp#6]
Cudafy doesn't seem to be maintained anymore and is not compatible with latest CUDA

**Comment by tramper2** [comment]
it will be very nice that support CUDA

**Comment by cbovar** [comment]
I am currently working on another GPU implementation using https://github.com/kunzmi/managedCuda. The branch is https://github.com/cbovar/ConvNetSharp/tree/GPU. You can try to run GPU MNIST demo: https://github.com/cbovar/ConvNetSharp/tree/GPU/Examples/GPUMnistDemo

So far only ConvLayer runs on GPU and the implementation is naive.

**Comment by omittones** [comment]
@cbovar Hey, thanks for the library. One small issue, there are two branches Gpu and GPU. Can you delete the Gpu (lowercase) branch, sometimes it overwrites the GPU branch when cloning on Windows. Thanks.

**Comment by cbovar** [comment]
I deleted 'Gpu' branch.

I'm about to commit a new version of ConvNetSharp that uses nvidia Cudnn library when running on GPU. It is much faster than what you can find in the current GPU branch (hand coded kernels).
