### ISSUE TITLE
Cuda / CuDNN does not work if project is created with NuGet packages

### ISSUE THREAD

**Issue by ammoniak** [cbovar/ConvNetSharp#65]
I created an empty solution, added a new project and added the NuGet-Packages.

Then I added the example code from: https://github.com/cbovar/ConvNetSharp
It works fine with CPU, but as soon as I try to run it GPU it does not find the DLL. If I switch the build to x64 it seems to find the dll, but an exception is thrown:

> System.NotImplementedException occurred
  HResult=0x80004001
  Message=The method or operation is not implemented.
  Source=ConvNetSharp.Volume
  StackTrace:
   at ConvNetSharp.Volume.Single.VolumeBuilder.SameAs(VolumeStorage`1 example, Shape shape)
   at ConvNetSharp.Core.Layers.LayerBase`1.DoForward(Volume`1 input, Boolean isTraining)
   at ConvNetSharp.Core.Net`1.Forward(Volume`1 input, Boolean isTraining)
   at XXX.Program.Main(String[] args) in C:\Users\XXX\documents\visual studio 2017\Projects\XXX\XXX\Program.cs:line 41

on the line:
`var prob = net.Forward(x);`

**Comment by ammoniak** [comment]
Note: Cloning the github repository works. I can compile and run the examples without any problem.

**Comment by raBpywa** [comment]
Maybe you should add in your project

> `BuilderInstance.Volume = new VolumeBuilder();`

**Comment by cbovar** [comment]
I think @raBpywa is right.

Do you have any ideas how to make this better ? First thing would be updating the error message.

**Comment by ammoniak** [comment]
Yes @raBpywa is right. This solves the problem. Can you add this to the example? Or to the GPU-Part:
https://github.com/cbovar/ConvNetSharp#gpu
It's not just switching the namespaces... On the other hand, adding the BuilderInstance might be a good idea for the CPU-Version as well.

Btw. I really like your project! Thanks for the time and effort you put into this.
