### ISSUE TITLE
Save and Load Serialization.

### ISSUE THREAD

**Issue by huynhvanvuong91** [cbovar/ConvNetSharp#67]
Current, I doing test program MnistDemo.GPU but when I Load file *.json them program error.
![image](https://user-images.githubusercontent.com/32187190/30770758-08aee4e0-a063-11e7-98e2-1ccf935d2c4a.png)

Please help me solution.

Thanks.

**Comment by cbovar** [comment]
I will at that when I'll be back from holidays

**Comment by cbovar** [comment]
Serialization tests should be made generic to detect such error earlier

**Comment by Diapa** [comment]
I have this problem. How do I fix it? I installed with nuget and I use regressionlayer. The exception seems to come from https://github.com/cbovar/ConvNetSharp/blob/f89f9649a63a924646ad2183f560849404bf89a0/src/ConvNetSharp.Core/Layers/LayerBase.cs#L101

**Comment by cbovar** [comment]
Hi @Diapa ,
Could you try with the new nuget package (0.4.3) ?

**Comment by Diapa** [comment]
Yes it works now thank you, but using this version GPU doesn't work. I get the same problem, but only using GPU. Additionally I get an ArgumentNullException when adding a convolutional layer to the network (only GPU version). It comes from ConvNetSharp.Volume.GPU.Single.Volume.LoadKernels().

**Comment by cbovar** [comment]
Do you have a minimal code that reproduces this error?

**Comment by Diapa** [comment]
Maybe there's some problem with my CUDA/cudnn installation if you don't get this problem... But I was able to run GPU version with v0.4.2.

```
using ConvNetSharp.Core;
using ConvNetSharp.Core.Layers;
using ConvNetSharp.Volume.GPU.Single;

namespace m
{
    class Program
    {
        static void Main(string[] args)
        {
            BuilderInstance.Volume = new VolumeBuilder();

            Net<float> net = new Net<float>();
            net.AddLayer(new InputLayer<float>(20, 20, 3));
            net.AddLayer(new ConvLayer<float>(5, 5, 48)); //System.ArgumentNullException
            /*
            System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
            System.IO.StreamReader..ctor(Stream stream)
            ConvNetSharp.Volume.GPU.KernelLoader`1.LoadKernel(String name, Stream stream)
            ConvNetSharp.Volume.GPU.Single.Volume.LoadKernels()
            ConvNetSharp.Volume.GPU.Single.VolumeBuilder.Random(Shape shape, Double mu, Double std)
            ConvNetSharp.Core.Layers.ConvLayer`1.UpdateOutputSize()
            ConvNetSharp.Core.Net`1.AddLayer(LayerBase`1 layer)
            [row 15 in this file]
            */
        }
    }
}

```
