### ISSUE TITLE
Simple RNN?

### ISSUE THREAD

**Issue by GospodinNoob** [cbovar/ConvNetSharp#72]
Are there any plans to add simple RNN layers?
V(tanh(Ux + Ws))

**Comment by cbovar** [comment]
Hi. I don't have enough time to work on this currently.
One way to do it would be writing the RNN equations using the pure Flow approach.
I'll tag it as 'help wanted for now'.

**Comment by GospodinNoob** [comment]
Thanks for the answer. Then I will try to write it myself) I hope, it will work)

**Comment by GospodinNoob** [comment]
@cbovar I wrote the code. And it works in some tasks. But some values in the matrix may be very big (500-800). And when I try to calculate Softmax backward step, it computes the Infinity (double). The problem is that it is the correct answer (i checked the same task in python code). Have you any ideas how to fix it?

**Comment by cbovar** [comment]
That would be interesting to see two projects (python and C#) doing exactly the same task in order to understand what's wrong.
Are you using ConvNetSharp.Flow to create the RNN?
