### ISSUE TITLE
Taking data from video stream

### ISSUE THREAD

**Issue by PradiptaPN** [cbovar/ConvNetSharp#80]
Hi, first of all thank you for providing wonderful deep learning tools.

I am currently working on some projects that require me to classify image from video, such as face. I have trained the network based on MnistDemo example and saved it to json file so i can use it on main program.

my questions are:

1. how can i set image taken from video as input data?
2. Should i use MnistDemo classes such as circular buffer and dataset?

thank you for your support

**Comment by cbovar** [comment]
Hi,

> 1. How can I set image taken from video as input data?

a. Get frames from the video (as images)
b. Create volumes from images
c. Feed volumes to network and do the training / inference

> 2. Should I use MnistDemo classes such as circular buffer and dataset?

`MnistDemo.DataSet` has some specific part related to Mnist (`MnistEntry`) but you could create you own simple DataSet maybe like `ConvNetSharp.Performance.Tests.Set`:

```c#
    public class Set
    {
        public Volume<double>[] Inputs { get; set; }
        public Volume<double> Outputs { get; set; }
    }
```

`CircularBuffer `are just used to so some moving average of the testing and training accuracy. It's up to you to use it but it's not a must for your project.

**Comment by PradiptaPN** [comment]
thank you for your answer :D

**Comment by PradiptaPN** [comment]
sorry for asking again, is there any documentation on how to make volumes from images? somehow even after i convert images to double array, it returns error about incompatible dimensions provided
