### ISSUE TITLE
Confidence level of each classification

### ISSUE THREAD

**Issue by PradiptaPN** [cbovar/ConvNetSharp#82]
Hi, thanks again for the help for the other day

is there any way to display confidence level of each label when doing classification? 

for example:

Pict X is a dog, confidence level: 90%
Pict X is a human, confidence level: 100%

thanks for the support :)

**Comment by cbovar** [comment]
Hi,

If your last layer is a SoftmaxLayer, it already output confidence level for each class. 
`Net.GetPrediction()` is just a convenience method to return the prediction that has the highest confidence level. ([see here](https://github.com/cbovar/ConvNetSharp/blob/master/src/ConvNetSharp.Core/Net.cs#L60))

**Comment by PradiptaPN** [comment]
Thank you very much for the explanation :D
